name: Caller Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
     
jobs:
  job1:
     uses: SamaRamya/Centralized-workflow1/.github/workflows/gradle.yml@main
     with:
       dockerimage: "stellantis-harbor/java8-gradle7-node16/v1.0/"
       

    
